### ISSUE TITLE
file not found while include content from a URI

### ISSUE THREAD

**Issue by ghost** [ZihoRo/gitbook-plugin-asciidoc-include#1]
doesn't work while include content from a URI, such as 

README.adoc
```
include::https://raw.githubusercontent.com/asciidoctor/asciidoctor/master/README.adoc[]
``` 
Template render error: (/[book]/README.adoc)
  Error: ENOENT: no such file or directory, open '/[book]/https://raw.githubusercontent.com/asciidoctor/asciidoctor/master/README.adoc'

related AsciiDoc doc: http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#include-files

Thanks a lot~

**Comment by ZihoRo** [comment]
Thanks for the bug you submitted, and I will debug it this weekend.

**Comment by ZihoRo** [comment]
Can you speak chinese? I don't know how to speak in English. I'm using Google Translate. 
Please modify your `book.json`, i did not have to solve the problem under the gitbook syntax, because I don't know gitbook can support if the uri is not a git uri, and i don't have a uri can test this case. I need to refactor this plugin code so i did not post it. If you need to use it now, you can modify `plugins` and i will inform you after posting.
```json
{
    "pluginsConfig": {
        "asciidoc-include": {
            "syntax": "asciidoc"
        }
    },
   "plugins": [
        "asciidoc-include@git+https://github.com/ZihoRo/gitbook-plugin-asciidoc-include.git"
    ]
}
```

**Comment by ZihoRo** [comment]
I forgot to say that you must include `allow-uri-read` in the document
related AsciiDoc doc: [](http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#include-files)

**Comment by ZihoRo** [comment]
I forgot to say that you must include `allow-uri-read` in the document
related AsciiDoc doc: [http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#include-files](http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#include-files)

**Comment by Koriit** [comment]
This indeed fixed the issue. Could you, please, upload the new version to npm? Thank you!
